runChecks: true
actions:
  branch-protection-settings:
    branches:
      - name: main
        dismissStaleReviews: true
        requireBranchUpToDate: true
        checks:
          - name: Build & Test
            type: tests
  sync-code-owners:
    extraWriters: ["plastic-issuance-service-owners"]
